Medicard.WebUI/Areas/Doctor/Controllers/DoctorController.cs
using Medicard.Domain.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Medicard.WebUI.Areas.Doctor.Controllers
{
    public class DoctorController : Controller
    {
        private readonly MedicardDbContext _context;
        public DoctorController(MedicardDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.ToListAsync());
        }
    }
}

Medicard.WebUI/Controllers/ChatController.cs
using Medicard.Domain.Concrete;
using Medicard.Domain.Entities;
using Medicard.Services.Services.Interfaces;
using Medicard.WebUI.Hubs;
using Medicard.WebUI.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace Medicard.WebUI.Controllers
{
    public class ChatController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IChatService _chatService;

        public ChatController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager, IChatService chatService)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _chatService = chatService;
        }

        public async Task<IActionResult> AllChats(string search, string userName = "")
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var targetUser = await _userManager.FindByNameAsync(userName);
            var allUsers = await _chatService.GetAllTargetUsersBasedOnRole(currentUser);

            ViewData["Search"] = search;

            if (!String.IsNullOrEmpty(search))
            {
                allUsers = allUsers
                    .Where(user => user.ToString().ToLower().Contains(search.ToLower())).ToList();
            }

            var chatsViewModel = await _chatService.GetListChats(allUsers, currentUser);

            if(!string.IsNullOrEmpty(userName))
            {
                var messages = _chatService.GetAllMessages(currentUser, targetUser);

                ViewBag.Messages = messages;
                ViewBag.CurrentUser = currentUser;
                ViewBag.TargetUser = targetUser;

                ViewBag.UserName = userName;
            }

            return View(chatsViewModel);
        }

        [HttpPost]
        public IActionResult SwitchChat(string userName)
        {
            return this.RedirectToAction("AllChats", new { userName = userName });
        }

        public async Task<IActionResult> SendMessage(string Text, [FromServices] IHubContext<ChatHub> chat)
        {
            var sender = await _userManager.GetUserAsync(User);
            var message = _chatService.AddMessage(Text, sender);

            await chat.Clients.All.SendAsync("ReceiveMessage", message);

            return Ok();
        }
    }
}

Medicard.WebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@inject SignInManager<Medicard.Domain.Entities.User> SignInManager
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Medicard.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg" style="background-color:#01ABC2;">
          <div class="container-md">
           <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src = "/images/logo.PNG" style="width: 150px;"/></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                @await Html.PartialAsync("_NavbarPartial")
              </ul>
            </div>
            <ul class="navbar-nav">
                @await Html.PartialAsync("_LoginPartial")
            </ul>
            <ul class="navbar-nav">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Medicard - Copyright:
                    <a href="https://github.com/matviiv8" class="text-reset">
                        <i class="bi bi-github"></i>
                        Andrew Matviiv
                    </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>

Medicard.WebUI/Views/Shared/_NavbarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@inject SignInManager<Medicard.Domain.Entities.User> SignInManager
@inject IViewLocalizer Localizer

<li class="nav-item">
    <a class="nav-link text-white" asp-area="" asp-controller="Doctor" asp-action="AllDoctors"><i class="fas fa-user-md"></i> @Localizer["LinkToViewAllDoctors"]</a>
</li>
<li class="nav-item">
    <a class="nav-link text-white" asp-area="" asp-controller="Institution" asp-action="AllInstitutions"><i class="fas fa-building"></i> @Localizer["LinkToViewAllInstitutions"]</a>
</li>
@if (SignInManager.IsSignedIn(this.User))
{
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Appointment" asp-action="AllAppointments"><i class="fas fa fa-calendar"></i> @Localizer["LinkToViewAllAppointments"]</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" asp-area="" asp-controller="Chat" asp-action="AllChats"><i class="fas fa-comment"></i> @Localizer["Chats"]</a>
    </li>
    @if (this.User.IsInRole("Doctor") || this.User.IsInRole("Head doctor"))
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Patient" asp-action="AllPatients"><i class="fas fa-head-side-cough"></i> @Localizer["Patients"]</a>
        </li>
    }
    @if (this.User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <a class="nav-link text-white" asp-area="" asp-controller="Admin" asp-action="Statistics"><i class="fas fa-percent"></i> @Localizer["Statistics"]</a>
        </li>
    }
}

Medicard.WebUI/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
 
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
 
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();
}

 <ul class="navbar-nav">
    <form method="post" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path">
        <li class="nav-item">
                    <i class="fa fa-globe" style="color:white"></i>
            <select name="culture" onchange="this.form.submit();"
                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                    asp-items="cultureItems"  style="border:none;background-color:#01ABC2;color:white;"></select>
        </li>
    </form>
</ul>